"""License validation and business control logic.

This module implements the PrepLicense business rules:

LICENSE STATES (FSM):
  unused   -> License generated by admin, ready for student activation
  active   -> Student activated, can access prep resources
  expired  -> Interview date passed; auto-marked on validation
  revoked  -> Admin manually revoked; student loses access

VALIDATION RULES:
  - License must exist and belong to requesting student
  - Company name must match (case-insensitive)
  - Status must be 'active' (not unused, expired, or revoked)
  - Interview date must not be in the past (auto-expires if so)
  - All validated licenses passed to API endpoints

PLAN GENERATION CONTROL:
  - plan_generated flag is ONE-TIME per license
  - First check: plan_generation_allowed() returns False if already used
  - After generation: mark_plan_generated() sets flag to True
  - Prevents duplicate expensive LLM calls for same licensee:company:role
"""
from datetime import date

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.models.prep_license import PrepLicense


def validate_license(
    db: Session,
    license_key: str,
    student_id: int,
    company_name: str,
) -> PrepLicense:
    """Validate license for API access.
    
    Comprehensive validation including:
    - License exists and is unique
    - Belongs to requesting student
    - Company name matches (case-insensitive)
    - Status is 'active' (not unused, expired, revoked)
    - Interview date not in past (auto-expires if so)
    
    Args:
        db: Database session
        license_key: License key to validate
        student_id: Student claiming to use license
        company_name: Company for interview prep
        
    Returns:
        PrepLicense: Validated license object
        
    Raises:
        HTTPException(403): Any validation rule violated
    """
    # Find license by key first (never trust student_id alone)
    license = (
        db.query(PrepLicense)
        .filter(PrepLicense.license_key == license_key)
        .first()
    )
    
    if not license:
        raise HTTPException(
            status_code=403,
            detail="Invalid license key"
        )

    # License must be bound to the same student
    if license.student_id != student_id:
        raise HTTPException(
            status_code=403,
            detail="License does not belong to this student"
        )

    # Company must match license (case-insensitive)
    if (license.company_name or "").strip().lower() != (company_name or "").strip().lower():
        raise HTTPException(
            status_code=403,
            detail="License is not valid for this company"
        )
    
    # Check if license is revoked
    if license.status == "revoked":
        raise HTTPException(
            status_code=403,
            detail="License has been revoked"
        )
    
    # Auto-expire if interview date has passed
    today = date.today()
    if today > license.interview_date:
        license.status = "expired"
        db.commit()
        raise HTTPException(
            status_code=403,
            detail="License expired - interview date has passed"
        )
    
    # Check if license is active
    if license.status != "active":
        raise HTTPException(
            status_code=403,
            detail=f"License status is '{license.status}' - only 'active' licenses are valid"
        )
    
    return license


def check_plan_generation_allowed(license: PrepLicense) -> bool:
    """Check if plan generation is allowed (plan_generated flag is False).
    
    Returns True only if license.plan_generated=False (one-time only).
    """
    return not license.plan_generated


def mark_plan_generated(db: Session, license: PrepLicense) -> None:
    """Mark plan as generated for this license.
    
    Sets plan_generated=True to prevent multiple expensive LLM calls.
    Called by Celery worker after successful Gemini plan generation.
    """
    license.plan_generated = True
    db.commit()
