"""PrepLicense model for business usage control and interview preparation tracking.

This module defines the PrepLicense model which represents a single-owner SaaS license key.
NOTE: This is NOT user authentication. It is a BUSINESS CONTROL mechanism that tracks:
- Which student is using a license
- For which company interview
- With a deterministic expiration date
- And whether plan generation tokens have been spent

License Lifecycle:
  unused    -> generated by admin, awaiting student activation
  active    -> student activated with email, valid for prep work
  expired   -> auto-marked when interview_date passes
  revoked   -> admin-marked when student loses access

Key Fields:
  license_key:       Unique identifier (e.g., "GOOG-2026-X7K2Q9Z1")
  student_id:        NULL when unused, set when student activates
  company_name:      Interview target company (case-insensitive matching)
  interview_date:    Drives expiration and days_available calculation
  plan_generated:    One-time flag preventing duplicate expensive LLM calls
  status:            FSM: unused|active|expired|revoked
"""
from datetime import date, datetime

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from shared.db.base import Base


class PrepLicense(Base):
    """PrepLicense ORM model: Single-owner SaaS license key.
    
    Each license represents one student's interview prep for one company.
    Licenses are created by admins in bulk, then issued to students who activate them.
    """
    __tablename__ = "prep_licenses"

    id: Mapped[int] = mapped_column(primary_key=True)
    license_key: Mapped[str] = mapped_column(String(128), unique=True, index=True)
    # Unique identifier: format "COMPANY-YEAR-TOKEN" (e.g., "GOOG-2026-X7K2Q9Z1")
    
    student_id: Mapped[int | None] = mapped_column(ForeignKey("students.id"), nullable=True)
    # NULL when unused, populated when student activates license
    
    company_name: Mapped[str] = mapped_column(String(255))
    # Interview target company; must match target company in all queries
    
    role: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Optional role specification (e.g., "Backend Engineer", "Data Scientist")
    
    interview_date: Mapped[date] = mapped_column(Date)
    # Admin-specified interview date; drives automatic expiration and days_available calculation
    # When today > interview_date, license is auto-marked expired
    
    activated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # Timestamp when student activated (changed status from unused to active)
    
    status: Mapped[str] = mapped_column(String(20), default="unused")
    # FSM state: unused -> active -> expired (or revoked by admin)
    # Only status='active' are valid for prep work
    
    plan_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    # One-time flag: True after first plan generation for this license
    # Prevents multiple expensive Gemini API calls for same licensee/company/role combo
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    # Admin creation timestamp

    student: Mapped["Student"] = relationship(back_populates="prep_licenses")

