"""add_topic_progress_table

Revision ID: 157b1e3face7
Revises: db5e6c78e9eb
Create Date: 2026-05-25 11:19:30.673094
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157b1e3face7'
down_revision = 'db5e6c78e9eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
