"""add_topic_progress_table

Revision ID: db5e6c78e9eb
Revises: 006_feedback_analysis_cache
Create Date: 2026-05-22 22:25:12.941863
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db5e6c78e9eb'
down_revision = '006_feedback_analysis_cache'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('coding_pct', sa.Integer(), nullable=False),
    sa.Column('quiz_done', sa.Boolean(), nullable=False),
    sa.Column('concepts_read_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target_interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_progress_student_id'), 'topic_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_target_id'), 'topic_progress', ['target_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_topic_id'), 'topic_progress', ['topic_id'], unique=False)
    op.drop_index('idx_topic_content_student_topic', table_name='topic_content')
    op.drop_table('topic_content')
    op.alter_column('learning_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.create_table('topic_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='topic_content_pkey'),
    sa.UniqueConstraint('student_id', 'topic_id', name='topic_content_student_id_topic_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_topic_content_student_topic', 'topic_content', ['student_id', 'topic_id'], unique=False)
    op.drop_index(op.f('ix_topic_progress_topic_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_progress_target_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_progress_student_id'), table_name='topic_progress')
    op.drop_table('topic_progress')
    # ### end Alembic commands ###
