"""Migration: Add summary_generated column to learning_plans table.

Advisor Summary System:
- summary_generated=False: Skeleton is ready, summary not generated yet
- summary_generated=True: plan_summary has been generated by Celery task

This migration is safe: column has default FALSE and is nullable-safe for existing rows.
"""
import logging
from sqlalchemy import text

logger = logging.getLogger(__name__)


def migrate_add_summary_generated_column(connection):
    """Add summary_generated BOOLEAN column with default FALSE."""
    try:
        connection.execute(text("ALTER TABLE learning_plans ADD COLUMN summary_generated BOOLEAN DEFAULT FALSE"))
        connection.commit()
        logger.info("[MIGRATION] Added summary_generated column to learning_plans")
    except Exception as e:
        if "already exists" in str(e).lower() or "duplicate" in str(e).lower():
            logger.info("[MIGRATION] Column summary_generated already exists, skipping")
        else:
            logger.error(f"[MIGRATION] Error adding summary_generated column: {e}")
            raise


if __name__ == "__main__":
    from app.db.session import engine

    with engine.connect() as conn:
        migrate_add_summary_generated_column(conn)
        print("Migration complete")
